# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .asset import *
from .lineage import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_marmot.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_marmot.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "marmot",
  "mod": "index",
  "fqn": "pulumi_marmot",
  "classes": {
   "marmot:index:Asset": "Asset",
   "marmot:index:Lineage": "Lineage"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "marmot",
  "token": "pulumi:providers:marmot",
  "fqn": "pulumi_marmot",
  "class": "Provider"
 }
]
"""
)
