// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Marmot.Outputs
{

    [OutputType]
    public sealed class AssetSource
    {
        public readonly string Name;
        public readonly int? Priority;
        public readonly ImmutableDictionary<string, object>? Properties;

        [OutputConstructor]
        private AssetSource(
            string name,

            int? priority,

            ImmutableDictionary<string, object>? properties)
        {
            Name = name;
            Priority = priority;
            Properties = properties;
        }
    }
}
