// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Marmot.Outputs
{

    [OutputType]
    public sealed class AssetEnvironment
    {
        public readonly ImmutableDictionary<string, object>? Metadata;
        public readonly string Name;
        public readonly string Path;

        [OutputConstructor]
        private AssetEnvironment(
            ImmutableDictionary<string, object>? metadata,

            string name,

            string path)
        {
            Metadata = metadata;
            Name = name;
            Path = path;
        }
    }
}
