// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Marmot.Outputs
{

    [OutputType]
    public sealed class ExternalLink
    {
        public readonly string? Icon;
        public readonly string Name;
        public readonly string Url;

        [OutputConstructor]
        private ExternalLink(
            string? icon,

            string name,

            string url)
        {
            Icon = icon;
            Name = name;
            Url = url;
        }
    }
}
