// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface AssetEnvironment {
    metadata?: {[key: string]: any};
    name: string;
    path: string;
}

export interface AssetSource {
    name: string;
    priority?: number;
    properties?: {[key: string]: any};
}

export interface ExternalLink {
    icon?: string;
    name: string;
    url: string;
}

