// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Marmot.Inputs
{

    public sealed class ExternalLinkArgs : global::Pulumi.ResourceArgs
    {
        [Input("icon")]
        public Input<string>? Icon { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public ExternalLinkArgs()
        {
        }
        public static new ExternalLinkArgs Empty => new ExternalLinkArgs();
    }
}
