// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Lineage extends pulumi.CustomResource {
    /**
     * Get an existing Lineage resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Lineage {
        return new Lineage(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'marmot:index:Lineage';

    /**
     * Returns true if the given object is an instance of Lineage.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Lineage {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Lineage.__pulumiType;
    }

    public /*out*/ readonly resourceId!: pulumi.Output<string>;
    public readonly source!: pulumi.Output<string>;
    public readonly target!: pulumi.Output<string>;
    public /*out*/ readonly type!: pulumi.Output<string | undefined>;

    /**
     * Create a Lineage resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LineageArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.source === undefined) && !opts.urn) {
                throw new Error("Missing required property 'source'");
            }
            if ((!args || args.target === undefined) && !opts.urn) {
                throw new Error("Missing required property 'target'");
            }
            resourceInputs["source"] = args ? args.source : undefined;
            resourceInputs["target"] = args ? args.target : undefined;
            resourceInputs["resourceId"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        } else {
            resourceInputs["resourceId"] = undefined /*out*/;
            resourceInputs["source"] = undefined /*out*/;
            resourceInputs["target"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Lineage.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Lineage resource.
 */
export interface LineageArgs {
    source: pulumi.Input<string>;
    target: pulumi.Input<string>;
}
